export const crumbsToTranslate: Record<string, string> = {
  catalog: 'Catálogo',
  products: 'Produtos',
  'manage-variants': 'Variante',
  facets: 'Etiquetas',
  collections: 'Coleções',
  users: 'Usuários',
  administrators: 'Administradores',
  clients: 'Clientes',
  config: 'Configuração',
  myshop: 'Minha loja',
  channels: 'Canais',
  permissions: 'Permissões',
  pagemanagement: 'Gerenciamento de Páginas',
  images: 'Imagens',
  galery: 'Galeria',
  banners: 'Banners',
  dashboard: 'Painel',
  sales: 'Vendas',
  orders: 'Pedidos',
  promotions: 'Promoções',
  rating: 'Avaliações',
  refunds: 'Devoluções',
  logistic: 'Logítisca',
  address: 'Endereços',
  receipt: 'Recebimento',
  payment: 'Pagamento',
  shipping: 'Entrega',
  system: 'Sistema',
  process: 'Processo'
}
